revision: latest
name: buildkite-agent-metrics
namespace: buildkite
deployment:
  replicas: 1
  image: buildkite-agent-metrics
  buildkiteQueue: test
  buildkiteBackend: prometheus
  buildkiteInterval: 30s
  prometheusAddress: :8080
  prometheusPath: /metrics
imagePullPolicy: IfNotPresent
